switch("path", "$projectDir/../src")
switch("warning", "Deprecated:off")
switch("hint", "Conf:off")
switch("hint", "Link:off")
switch("outdir", "$projectDir/../bin")
switch("opt", "speed")
#switch("profiler", "on")
#switch("stacktrace", "on")
